wafflestudio/snutt-ios

SNUTT/STColorActionSheetPicker.swift, SNUTT/STColumnHeaderCollectionViewCell.swift, SNUTT/STColumnHeaderCollectionViewCell.xib, SNUTT/STCourseCellCollectionViewCell.swift, SNUTT/STCourseCellCollectionViewCell.xib, SNUTT/STEtcRouter.swift, SNUTT/STLecture.swift, SNUTT/STLectureSearchTableViewController.swift, SNUTT/STLoginViewController.swift, SNUTT/STRowHeaderCollectionViewCell.swift, SNUTT/STRowHeaderCollectionViewCell.xib, SNUTT/STSingleClass.swift, SNUTT/STSlotCellCollectionViewCell.swift, SNUTT/STTimetableCollectionView.swift, SNUTT/STTimetableLayout.swift, SNUTT/STTimetableTabViewController.swift, SNUTT/STUtil.swift
Using various techniques to optimize reload data of collection view in search tab
=> Timetable design & Optimization

SNUTT/STTimeActionSheetPicker.swift, SNUTT/STTimetableListController.swift, SNUTT/STTimetableManager.swift
https://fabric.io/wafflestudio/ios/apps/com.wafflestudio.snutt/issues/5a156c9561b02d480dff8d48
https://fabric.io/wafflestudio/ios/apps/com.wafflestudio.snutt/issues/5a1578f361b02d480d007f20
https://fabric.io/wafflestudio/ios/apps/com.wafflestudio.snutt/issues/5a15738561b02d480d00186c
https://fabric.io/wafflestudio/ios/apps/com.wafflestudio.snutt/issues/5a157aa361b02d480d00a047
=> 171122 bugfix

SNUTT/STTimetableListController.swift, SNUTT/STUtil.swift
=> add "new timetable" item for every semester

SNUTT.xcodeproj/project.pbxproj, SNUTT/SettingViewController.swift
현재 시간표가 아닌 다른 시간표의 테마를 수정하려고 하면 알럿 보여주게 변경
=> Fix theme setting bug (SNUTT-161)

SNUTT/Login.storyboard, SNUTT/STRegisterViewController.swift
=> 애플 회원가입 추가 (SNUTT-192)

SNUTT.xcodeproj/project.pbxproj
2021.08.20
SNUTT 2차 리뉴얼 
2.0.0 배포했습니다
=> release 2.0.0

SNUTT/Review/ReviewViewController.swift, SNUTT/STMainTabBarController.swift
Review tab 안에서 tab 누르면 메인 페이지로 이동
=> Review Tab (SNUTT-334)

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
- 아래 3개의 Deployment Target을 모두 14.0 이상으로 변경했습니다.
=> Deployment Target 14.0 이상으로 변경 [SNUTT-410]

.github/workflows/build.yml
- #56 에 의존하는 PR입니다.
- iOS 14 / 15 빌드 테스트를 위한 github actions를 추가했습니다.
=> iOS14/15 빌드 테스트 CI [SNUTT-411]

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/AppState.swift, SNUTT-2022/SNUTT/Assets/STColor.swift, SNUTT-2022/SNUTT/Assets/STFont.swift, SNUTT-2022/SNUTT/Models/Lecture.swift, SNUTT-2022/SNUTT/Views/Components/LectureDetailList.swift, SNUTT-2022/SNUTT/Views/Components/LectureDetails.swift, SNUTT-2022/SNUTT/Views/Components/TimetableList.swift, SNUTT-2022/SNUTT/Views/Components/TimetableListCell.swift, SNUTT-2022/SNUTT/Views/SNUTTApp.swift, SNUTT-2022/SNUTT/Views/Scenes/MyTimetableListScene.swift, SNUTT/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- #56 에 의존하는 PR입니다.
- `TimetableList`와 `TimetableListCell`, 그리고 임시로 `LectureDetails` 뷰를 추가했습니다.
- 모델은 따로 추가하지 않아서 Text 값들은 전부 하드코딩했습니다.
=> 타임테이블 리스트뷰 생성 [SNUTT-402]

SNUTT/SNUTT/STTimetableCollectionView.swift
=> fix(orig): fix autofit start-end value

SNUTT/SNUTT/STPeriod.swift, SNUTT/SNUTT/STSingleClassTableViewCell.swift, SNUTT/SNUTT/STSingleLectureTableViewController.swift, SNUTT/SNUTT/STTime.swift
- 오늘 논의한 내용대로, `startPeriod + duration - (isHalfPeriod ? 15/60 : 10/60)` 과 같이 실제 시간 보정을 해주었습니다.
=> 시간표 끝나는 시간 더 정확하게 변경 [SNUTT-420]

SNUTT/SNUTT/STLecture.swift, SNUTT/SNUTT/STPeriod.swift, SNUTT/SNUTT/STTimetableCollectionView.swift
- #65 에 추가된 0~23시 기능을 삭제했습니다.
- 이 PR은 중복 강의 제거 기능을 구현하는 `snutt-455`로 Merge됩니다
=> 0~23시 기능 삭제

SNUTT/SNUTT/STAccountSettingViewController.swift
- 앱 설정에서 이메일 변경하지 못하도록 수정했습니다.
=> 설정에서 이메일 변경하지 못하도록 변경 [SNUTT-460]

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Models/Setting.swift, SNUTT-2022/SNUTT/Models/TimetableSetting.swift, SNUTT-2022/SNUTT/ViewModels/SNUTTViewModel.swift, SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/LectureBlocks.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlocksLayer.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableGridLayer.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableZStack.swift, SNUTT-2022/SNUTT/Views/SNUTTApp.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/MyTimetableScene.swift, SNUTT-2022/SNUTT/Views/Scenes/TabScene.swift
- TabScene을 추가하고, 그 외 자잘한 리팩토링을 진행했습니다.
=> TabView 선언 방식 변경

SNUTT/SNUTT/STLectureDetailTableViewController.swift
=> 실제 강의는 "+ 시간 추가" 못하도록 변경

SNUTT/SNUTT/AppDelegate.swift, SNUTT/SNUTT/STPopupManager.swift, SNUTT/SNUTT/STTimetableTabViewController.swift, SNUTT/SNUTT/STUser.swift
Initialize 실행과 popup 뷰 로드 간에 쓰레드 이슈가 있던 것 같습니다. 클로저를 이용해 initialize 후에 popup 뷰가 로드되로록 수정했습니다,
=> Fix popup [SNUTT-472]

SNUTT/SNUTT.xcodeproj/project.pbxproj
Release 2.1.1
1. 팝업 추가
2. 중복된 시간표 덮어 쓰기
3. 위젯 테마 깨지는 것 수정
4. 검색뷰에서 강의 이름 길면 깨지는 것 수정
=> Release 2.1.1

SNUTT/SNUTT/Popup/PopupView.swift, SNUTT/SNUTT/Popup/PopupViewController.swift
- 팝업 이미지가 가변 사이즈로 구현되어 있던 것을 고정으로 수정하였습니다. 작은 디바이스에서 `당분간 보지 않기` label이 잘리지 않습니다.
=> 팝업 UI constraint 수정 [SNUTT-479]

SNUTT/SNUTT/Popup/PopupView.swift, SNUTT/SNUTT/Popup/PopupViewController.swift, SNUTT/SNUTT/STPopupManager.swift
=> Hotfix: 당분간 보지 않기 안 되는 버그 수정

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Models/MenuState.swift, SNUTT-2022/SNUTT/Modifiers/CircleBadge.swift, SNUTT-2022/SNUTT/Modifiers/CircleBadgeModifier.swift, SNUTT-2022/SNUTT/Services/CourseBookService.swift, SNUTT-2022/SNUTT/Services/GlobalUIService.swift, SNUTT-2022/SNUTT/Services/TimetableService.swift, SNUTT-2022/SNUTT/ViewModels/MenuSheetViewModel.swift, SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift, SNUTT-2022/SNUTT/Views/Components/MenuSheets/MenuCreateSheet.swift, SNUTT-2022/SNUTT/Views/Components/MenuSheets/MenuSection.swift, SNUTT-2022/SNUTT/Views/Components/MenuSheets/MenuSheet.swift, SNUTT-2022/SNUTT/Views/Components/NavBarButton.swift, SNUTT-2022/SNUTT/Views/Scenes/MenuSheetScene.swift, SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
검색할 때에도 비슷한 거 있으면 좋겠네요. 적어도 지금 무슨 학기 시간표를 검색하고 있는건지는 알 수 있도록.
https://user-images.githubusercontent.com/33917774/187515374-3958e1a6-09fd-4e6e-9074-7648164b6038.mov
=> 새로운 수강편람이 사용 가능한 경우 유저에게 알려주기

SNUTT-2022/SNUTT/Views/Components/Search/SearchTips.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/FilterSheetScene.swift, SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift
=> 강의 검색 페이지에서 상단에 빈 공간 생기는 문제 해결

.github/workflows/build.yml, SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Info.plist, SNUTT-2022/SNUTTTests/LectureRepositoryTests.swift, SNUTT-2022/SNUTTTests/TestUtils.swift, SNUTT-2022/SNUTTTests/TimetableRepositoryTests.swift, SNUTT-2022/SNUTTUITests/SNUTTUITests.swift, SNUTT-2022/SNUTTUITests/SNUTTUITestsLaunchTests.swift
- CI를 고치기 위한 PR입니다.
- DebugConfig.xcconfig에 ACCESS_TOKEN_TEST 아이템을 추가했습니다. 이 토큰은 DEV 서버에서 만든 테스트용 계정입니다. 이 파일은 DM으로 공유드릴게요.
=> Secrets 추가 및 테스트 작성

.github/workflows/build.yml, SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Info.plist, SNUTT-2022/SNUTT/Repositories/AuthRepository.swift, SNUTT-2022/SNUTT/Repositories/Dto/AuthDto.swift, SNUTT-2022/SNUTT/Repositories/Router/AuthRouter.swift, SNUTT-2022/SNUTTTests/AuthRepositoryTests.swift, SNUTT-2022/SNUTTTests/LectureRepositoryTests.swift, SNUTT-2022/SNUTTTests/TestUtils.swift, SNUTT-2022/SNUTTTests/TimetableRepositoryTests.swift, SNUTT-2022/SNUTTUITests/SNUTTUITests.swift, SNUTT-2022/SNUTTUITests/SNUTTUITestsLaunchTests.swift
- #119 에서 분기한 브랜치입니다. Files Changed에 섞여있을 수 있으니 유의해주세요.
- DTO
- Router
- Repository
- Test
작성했습니다.
후속 PR이 계속 올라올 예정입니다.
=> Auth Repository 구현

SNUTT-2022/SNUTT/Services/TimetableService.swift
- 앱을 처음 시작할 때 시간표가 타닥 하고 바뀌는 문제를 수정했습니다.
=> UserDefault 시간표 업데이트 관련 버그 수정

SNUTT-2022/SNUTT/Views/SNUTTView.swift
- 로그아웃 - 재로그인 시 설정 탭에서 시작하는 문제를 수정했습니다.
=> 로그인시 시간표 화면으로 이동하도록 변경

SNUTT-2022/SNUTT/Views/Scenes/FilterSheetScene.swift
- #132 의 수정사항을 `FilterSheet`에도 적용했습니다.
=> 필터 애니메이션 버그 수정

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Repositories/CourseBookRepository.swift, SNUTT-2022/SNUTT/Repositories/Router/CourseBookRouter.swift, SNUTT-2022/SNUTT/Services/CourseBookService.swift, SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift, SNUTT-2022/SNUTT/Views/Components/WebViews/SyllabusWebView.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
=> 강의계획서 웹뷰 추가

.github/CODEOWNERS, LICENSE, README.md
- 여러 템플릿을 참고해서 리드미 파일을 만들었습니다. [이곳](https://github.com/wafflestudio/snutt-ios/tree/shp7724/readme)에서 확인 가능합니다.
- @chaemin2001 님의 원활한 온보딩을 위해, fastlane을 사용한 프로젝트 세팅 방법을 README에 추가해두었습니다. (#160 이 머지되었다는 전제가 깔려있습니다.)
- CODEOWNERS, LICENSE 파일도 추가했습니다.
=> Add README.md, LICENSE, CODEOWNERS

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Extensions/View+Screenshot.swift, SNUTT-2022/SNUTT/Info.plist, SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
Resolves https://github.com/wafflestudio/snutt-ios/issues/141
=> 시간표 스크린샷 저장/공유 기능

README.md
=> Update readme acknowledgment

SNUTT-2022/SNUTTTests/AuthRepositoryTests.swift
- #153 머지 이후로 테스트가 터져서 고쳤습니다.
- 우선적으로 머지 부탁드려요.
=> Fix test failure

SNUTT-2022/SNUTT/Views/Components/Search/SearchBar.swift
- https://wafflestudio.slack.com/archives/C0PAVPS5T/p1668233358007339?thread_ts=1668232199.124749&cid=C0PAVPS5T
=> Fix filter sheet keyboard issue

SNUTT-2022/SNUTT/Views/Components/LectureTimePicker.swift
=> Fix LectureTimePicker UI issue

SNUTT-2022/SNUTT/Repositories/Dto/AuthDto.swift, SNUTT-2022/SNUTT/Repositories/UserRepository.swift
DeviceResponseDto 를 생성해 response decoding 에러를 고쳤습니다
=> Fix device api response decoding

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Views/Components/EmptyLectureList.swift, SNUTT-2022/SNUTT/Views/Components/LectureList.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlock.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureListScene.swift
- 시간표가 비어있는 경우 강좌 목록 화면에서 보여줄 View 추가
- 시간표 블럭에서 텍스트 가운데 정렬 어긋난 부분 수정
=> 시간표가 비어있는 경우 강좌 목록 View 추가

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift, SNUTT-2022/fastlane/Fastfile
- debug symbol 파일을 crashlytics에 업로드하는 빌드 스크립트를 추가했습니다.
=> Firebase Crashlytics 연결

SNUTT-2022/SNUTT/Models/Lecture.swift
- `colorIndex`를 0으로 초기화해서 custom color를 사용하도록 변경해주었습니다.
=> 임시 강의 색상 수정

SNUTT-2022/SNUTT/Views/Components/NotificationList.swift
원래 @chaemin2001 님 태스크이긴 한데, 배포를 곧 해야해서 제가 수정했습니다.
근데 저도 갑자기 해당 이슈가 재현이 안돼서, 테스트는 못해봤어요. 맞는지 잘 확인해주시면 감사하겠습니다.
Resolves #169
=> Notification 뷰 여백 수정

SNUTT-2022/SNUTT/AppState/States/PopupState.swift, SNUTT-2022/SNUTT/Models/Popup.swift, SNUTT-2022/SNUTT/Repositories/Dto/PopupDto.swift, SNUTT-2022/SNUTT/Services/PopupService.swift, SNUTT-2022/SNUTT/Views/Components/PopupView.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/PopupScene.swift
- 당분간 보지 않기를 눌러도 팝업이 번갈아가면서 무한히 뜨는 버그가 발견되어 팝업 기능을 전반적으로 리팩토링했습니다.
1. dto -> model로 변환될 때 nil값을 가진 hiddenDays가 0으로 초기화되는 이슈를 수정했습니다.
2. `currentPopupList`에 `filter`를 건 뒤에 UserDefault에 저장하면서, 기존에 저장된 팝업들이 덮어씌워지는 이슈를 수정했습니다.
3. 마지막 닫기 버튼을 눌렀을 때 애니메이션이 적용되지 않던 문제를 수정했습니다.
1. `shouldShowPopup`, `currentIndex`를 삭제하고 `currentList`를 중심으로 모든 로직들이 돌아가게끔 변경했습니다.
2. `SNUTTView`에 있던 일부 팝업 관련 로직을 모두 `PopupScene`으로 옮겼습니다.
3. View를 인자로 받던 함수를 리팩토링했습니다.
=> Refactor and bug fixes for popup

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/AppEnvironment.swift, SNUTT-2022/SNUTT/AppState/States/SystemState.swift, SNUTT-2022/SNUTT/Extensions/ColorScheme.swift, SNUTT-2022/SNUTT/Repositories/UserDefaultsRepository.swift, SNUTT-2022/SNUTT/Services/GlobalUIService.swift, SNUTT-2022/SNUTT/ViewModels/SettingViewModel.swift, SNUTT-2022/SNUTT/Views/Components/WebViews/ReviewWebView.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/ColorSchemeSettingScene.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
https://user-images.githubusercontent.com/33917774/207481177-7e965548-e9ac-452a-814b-aa8379158a67.mov
=> 색상 모드 수동 설정 가능하도록 변경

SNUTT-2022/Gemfile.lock, SNUTT-2022/fastlane/Fastfile, SNUTT-2022/fastlane/Pluginfile
- App Store Connect에서 앱 버전을 자동으로 업데이트해주기 위한 파라미터를 추가합니다.
=> Add app_version parameter to fastlane

.github/workflows/build.yml
=> Secret 변수명 변경

SNUTT-2022/SNUTT/Views/Scenes/ResetPasswordScene.swift
- Release 아카이빙 오류를 수정하는 픽스입니다. 별 수정사항 없어서 바로 머지할게요.
- @peng-u-0807 확인 바랍니다.
=> Wrap debug-only property with DEBUG flag

SNUTT-2022/SNUTT/Models/Lecture.swift, SNUTT-2022/SNUTT/Models/TimePlace.swift, SNUTT-2022/SNUTT/Models/TimetableConfiguration.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/Utils/TimeUtils.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/LectureBlocks.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/TimetableSettingScene.swift
[관련 스레드](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1673276131952679)
- 시간표 꽉찬모드를 구현할 수 있는 방법 중 하나를 테스트해보는 PR입니다.
https://user-images.githubusercontent.com/33917774/211619491-e910c329-0ffd-413d-a314-9072081d8eb6.mov
=> Support compact mode (a.k.a 꽉찬모드) as a PoC

SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift, SNUTT-2022/SNUTT/ViewModels/SearchSceneViewModel.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift, SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift
- #207 에서 리뷰 부분만 반영했습니다.
- 바로 머지하고 배포 진행할게요.
=> 이메일 미인증시 CTA 개선 (2)

SNUTT-2022/SNUTT/Views/Components/EmptyLectureList.swift, SNUTT-2022/SNUTT/Views/Scenes/BookmarkScene.swift
Testflight Release 오류 해결을 위한 Debg Flag을 추가했습니다.
=> Add Debug Flag

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/States/TimetableState.swift, SNUTT-2022/SNUTTWidget/SNUTTWidgetProvider.swift, SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableWidgetEntryView.swift
- UserDefaults에 있던 `timetableConfig`를 사용하도록 변경했습니다.
=> Fix Widget `timetableConfig` issue

SNUTT-2022/SNUTT/Repositories/NetworkConfiguration.swift, SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift, SNUTT-2022/SNUTT/ViewModels/SettingViewModel.swift
- 에러 로깅을 위해 메타데이터를 쿠키에 추가했습니다.
=> Add app metadata cookie for webview

.github/workflows/build.yml, SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/ViewModels/FilterSheetViewModel.swift, SNUTT-2022/SNUTT/ViewModels/MenuSheetViewModel.swift
Fix https://wafflestudio.slack.com/archives/C8M9NUBBR/p1673868878983709
=> 애니메이션 버그 수정

SNUTT-2022/SNUTT/Extensions/View+Screenshot.swift, SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
Fix https://wafflestudio.slack.com/archives/C8M9NUBBR/p1677853209331279
=> Use preferredColorScheme when taking screenshot

SNUTT-2022/SNUTT/Views/Components/UserSupportView.swift
Fix https://wafflestudio.slack.com/archives/C0PAVPS5T/p1678180931399309
=> Add loading spinner when submitting user feedback

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Services/TimetableService.swift, SNUTT-2022/SNUTT/Views/Components/TimeRangeSlider.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/TimetableSettingScene.swift
- 슬라이더를 구현했습니다.
- 진동 피드백도 넣으니까 좋네요.
https://user-images.githubusercontent.com/33917774/224528834-56485286-01d6-48c6-87f2-8d6754fd2df1.mov
=> New TimeRangeSlider for `minHour` and `maxHour`

SNUTT-2022/SNUTT/Repositories/Router/LectureRouter.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
=> Remove UUID for lecture_id Field

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/AppEnvironment.swift, SNUTT-2022/SNUTT/AppState/AppState.swift, SNUTT-2022/SNUTT/AppState/States/DebugState.swift, SNUTT-2022/SNUTT/AppState/States/MenuState.swift, SNUTT-2022/SNUTT/AppState/States/PopupState.swift, SNUTT-2022/SNUTT/AppState/States/SearchState.swift, SNUTT-2022/SNUTT/AppState/States/SystemState.swift, SNUTT-2022/SNUTT/AppState/States/TimetableState.swift, SNUTT-2022/SNUTT/AppState/States/UserState.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogEntry.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogEntryView.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogListScene.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogStore.swift, SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
- 디버깅을 위해 네트워크 요청을 로깅합니다.
- 로그는 메모리에 저장됩니다.
- 디버그 빌드에서만 사용 가능합니다.
https://user-images.githubusercontent.com/33917774/237046079-f56a4b6b-dc04-4606-8525-9dc631f2881f.MP4
=> Network Inspector for debug builds

SNUTT-2022/SNUTT/Models/Lecture.swift
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1685550681352609
=> Remove duplicate from places string

SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogEntry.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogEntryView.swift, SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogStore.swift
- 쿼리파람 안보이는 것 수정
- Time Metrics 추가
=> Enhance network inspector

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Assets/STColor.swift, SNUTT-2022/SNUTT/Models/ErrorCode.swift, SNUTT-2022/SNUTT/Repositories/AuthRepository.swift, SNUTT-2022/SNUTT/Repositories/Dto/AuthDto.swift, SNUTT-2022/SNUTT/Repositories/Dto/UserDto.swift, SNUTT-2022/SNUTT/Repositories/Router/AuthRouter.swift, SNUTT-2022/SNUTT/Repositories/Router/UserRouter.swift, SNUTT-2022/SNUTT/Repositories/UserRepository.swift, SNUTT-2022/SNUTT/Services/AuthService.swift, SNUTT-2022/SNUTT/Services/UserService.swift, SNUTT-2022/SNUTT/ViewModels/AccountSettingViewModel.swift, SNUTT-2022/SNUTT/ViewModels/OnboardViewModel.swift, SNUTT-2022/SNUTT/Views/Components/AnimatedTextField.swift, SNUTT-2022/SNUTT/Views/Components/EmailVerificationView.swift, SNUTT-2022/SNUTT/Views/Components/SignUpView.swift, SNUTT-2022/SNUTT/Views/Components/VerificationCodeView.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/LoginScene.swift, SNUTT-2022/SNUTT/Views/Scenes/OnboardScene.swift, SNUTT-2022/SNUTT/Views/Scenes/ResetPasswordScene.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/AccountSettingScene.swift
수정사항: ![image](https://github.com/wafflestudio/snutt-ios/assets/70614553/6bc31bd7-1738-48ac-83f4-8aa6c58e116e)
=> Add email verification step to local id registration

SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SNUTT-2022/SNUTT/Models/Lecture.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Components/LectureDetail/DetailLabel.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
- `LectureDetailScene`: `정원` -> `정원(재학생)`
=> Add non-freshman quota label for lecture

SNUTT-2022/SNUTT/Views/Components/SignUpView.swift
- https://wafflestudio.slack.com/archives/C0PAVPS5T/p1690935232922619
=> Fix SignupView button disablement

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SNUTT-2022/SNUTT/AppState/AppEnvironment.swift, SNUTT-2022/SNUTT/Info.plist, SNUTT-2022/SNUTT/Models/ErrorCode.swift, SNUTT-2022/SNUTT/Repositories/Dto/ConfigDto.swift, SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift, SNUTT-2022/SNUTT/Services/FriendsService.swift, SNUTT-2022/SNUTT/Services/VacancyService.swift, SNUTT-2022/SNUTT/ViewModels/FriendsViewModel.swift, SNUTT-2022/SNUTT/Views/AppDelegate.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
- 설정에 친구 버튼 임시로 추가해놨습니다.
- 친구기능은 `FEATURE_RN_FRIENDS` 라는 피쳐플래그 사용해서 천천히 구현해나갈 예정입니다. 릴리즈 코드에는 반영되지 않습니다.
- ReactNativeKit이 ipa에 포함되어 앱 사이즈는 수메가바이트에서 수십메가바이트 정도 증가할 것으로 예상됩니다.
RN은 Debug/Release 두 가지 버전으로 빌드했고, 이 레포에는 항상 Release 버전만 포함됩니다.
RN 개발자 도구가 포함된 Debug 빌드를 쓰고 싶으면 아래 방식으로 직접 전환해야 합니다. @woohm402 
https://github.com/wafflestudio/snutt-ios/assets/33917774/141bfb6f-a512-466d-8209-1dbec744b8a5
도메인은 `FriendsScene.swift` 파일의 config 사용해서 바꿀 수 있습니다.
=> Add ReactNativeKit support for friends feature

SNUTT-2022/SNUTT/Models/User.swift, SNUTT-2022/SNUTT/Repositories/Dto/UserDto.swift, SNUTT-2022/SNUTT/Repositories/Router/UserRouter.swift, SNUTT-2022/SNUTT/Repositories/UserRepository.swift, SNUTT-2022/SNUTT/Services/UserService.swift
- 기존의 `GET /v1/user/info`를 `GET /v1/users/me`로 대체
- `PATCH /v1/users/me`에 대한 지원 추가
=> Add support for `/v1/users/me`

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> Upgrade ReactNativeKit 

SNUTT-2022/SNUTT/Repositories/UserDefaultsRepository.swift, SNUTT-2022/SNUTT/Services/VacancyService.swift, SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift, SNUTT-2022/SNUTT/Views/Components/Vacancy/VacancyBanner.swift, SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
=> Remove x button from vacancy banner

SNUTT-2022/SNUTT/Extensions/View+Screenshot.swift, SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
=> Resize screenshot bounds when banner is open

SNUTT-2022/SNUTT/Models/TimePlace.swift, SNUTT-2022/SNUTT/Models/Timetable.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/Services/LectureService.swift, SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
- `LectureDetailScene` 내에서 강의 제목이 비어있는 경우와 강의 내부에서 `Timeplace`가 겹치는 경우 alert가 제대로 뜨지 않는 문제를 수정하였습니다.
=> Fix alert not showing in `LectureDetailScene`

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/AppEnvironment.swift, SNUTT-2022/SNUTT/Services/FriendsService.swift, SNUTT-2022/SNUTT/ViewModels/FriendsViewModel.swift, SNUTT-2022/SNUTT/Views/AppDelegate.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift, SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift
- `FEATURE_RN_FRIENDS` flag를 제거했습니다
=> Remove `FEATURE_RN_FRIENDS` flag

SNUTT-2022/SNUTT/Models/SearchTag.swift, SNUTT-2022/SNUTT/Repositories/Dto/SearchTagDto.swift, SNUTT-2022/SNUTT/Repositories/Router/SearchRouter.swift
=> Remove search tag `instructor`

SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1701444940211509
=> RN 피쳐 플래그 추가

SNUTT-2022/SNUTT/Views/Components/Timetable/LectureBlocks.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
https://wafflestudio.slack.com/archives/C8M9NUBBR/p1702013429336789
https://github.com/wafflestudio/snutt-ios/assets/33917774/d2b53f3f-33e0-4efb-ab1f-cc66d0f0b1b2
=> Fix timerange issue

SNUTT-2022/SNUTT/Views/Components/Search/SearchTips.swift
- 강의실 건물 동/호수 검색 지원에 따른 search tips 문구 수정
=> Add search tips for place

.github/workflows/deploy.yml
appstore connect 업로드 실패하는 문제 수정 시도..
=> Fastlane 업데이트

SNUTT-2022/SNUTT/Models/TimePlace.swift, SNUTT-2022/SNUTT/Models/Timetable.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/Utils/TimeUtils.swift, SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Components/LectureDetail/EditableFields.swift, SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift, SNUTT-2022/SNUTT/Views/Components/Vacancy/VacancyLectureCell.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureTimeSheetScene.swift, SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableAccessoryCircularView.swift, SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableCompactWidgetView.swift
- `start_time`과 `end_time`을 `startMinute`, `endMinute`로 대체하였습니다
- 대체하면서 사용되지 않는 `TimeUtils`쪽 코드 정리
=> Replace start_time, end_time with startMinute, endMinute

SNUTT-2022/SNUTT/Views/Components/SignUpView.swift
- 기존 회원이 아이디/비밀번호 추가하는 경우에도 이메일 인증 화면으로 이동되던 문제를 수정했습니다
=> Fix unexpected navigation to `EmailVerificationView`

SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
=> Fix unexpected UI layout of toolbar (`TimetableScene`)

SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift
=> Fix unexpected UI layout of toolbar (`TimetableScene`) (1)

SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift
이거 이렇게만 고치면 되나 ..? 테스트할 수 있는 케이스를 모르겠어서ㅜ
=> Change Content of Server Error Alert

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Models/Building.swift, SNUTT-2022/SNUTT/Models/TimePlace.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/Repositories/LectureRepository.swift, SNUTT-2022/SNUTT/Repositories/Router/BuildingRouter.swift, SNUTT-2022/SNUTT/Services/LectureService.swift, SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
- `Lecture`의 `LectureBuilding` 정보를 별도 api 호출로 받아오도록 수정 ([관련 슬랙](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1712219417042559))
=> Separate getting `LectureBuilding` info api

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SNUTT-2022/SNUTT/Services/FriendsService.swift, SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift
EventEmitter 구현체는 여기에 있습니다
https://github.com/wafflestudio/ios-rn-prebuilt/tree/main/ReactNativeKit/ReactNativeKit/EventEmitter
=> RN Event Emitter POC

SNUTT-2022/SNUTT/Views/Components/UserSupportView.swift
- [관련 슬랙](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1714277873740579)
=> Change `UserSupportView` info text

SNUTT-2022/SNUTT/Models/Popup.swift, SNUTT-2022/SNUTT/Repositories/Dto/PopupDto.swift, SNUTT-2022/SNUTT/Services/PopupService.swift
- `hidden_days`랑 `image_url` camelCase로 변경
- 하는 김에 다른 필드명도 동일하게 수정했어요
- [팝업 로직 변경](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1712758540760669?thread_ts=1712730879.668129&cid=C0PAVPS5T)
=> Fix `PopupDto` field name + display logic

SNUTT-2022/SNUTT/Views/Components/SignUpView.swift, SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
- [관련 슬랙](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1717491592060939?thread_ts=1716815045.027249&cid=C0PAVPS5T)
- 개인정보처리방침 수정하면서 같이 수정해야 하는 라벨들 문구 변경
=> Change label text

SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift
- 강의평 화면에서 BottomSheet가 제대로 보이지 않는 문제 수정
=> Fix webview area

SNUTT-2022/SNUTT/Services/LectureService.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
- [관련 슬랙](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1722948782395609)
- 시간표에 추가된 강의와 추가되지 않은 강의에 대한 구분이 없었던 문제
=> Fix fetching id of `EvLecture`

SNUTT-2022/SNUTT/Models/SearchTag.swift, SNUTT-2022/SNUTT/Repositories/Dto/SearchTagDto.swift, SNUTT-2022/SNUTT/Repositories/Router/SearchRouter.swift, SNUTT-2022/SNUTT/Services/SearchService.swift, SNUTT-2022/SNUTT/Views/Components/FilterSheetContent.swift, SNUTT-2022/SNUTT/Views/Components/Search/SearchTagsScrollView.swift
- 검색 필터에 "정렬 기준" 추가
- 겸사겸사 강의 검색 결과 pagination 도중 일부 cell이 빈칸으로 뜨는 문제 수정
=> Add `sortCriteria` tag to searching lectures

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/AppState/AppEnvironment.swift, SNUTT-2022/SNUTT/AppState/States/SystemState.swift, SNUTT-2022/SNUTT/Repositories/Dto/ConfigDto.swift, SNUTT-2022/SNUTT/Services/GlobalUIService.swift, SNUTT-2022/SNUTT/Views/Components/NoticeView.swift, SNUTT-2022/SNUTT/Views/SNUTTView.swift
- `NoticeView`를 위해 config 불러올 Service가 마땅치 않아서 가장 맥락 맞아보이는 `GlobalUIService` 쪽에다 붙였습니다
=> Add `NoticeView`

SNUTT-2022/SNUTT/ViewModels/OnboardViewModel.swift, SNUTT-2022/SNUTT/Views/Scenes/OnboardScene.swift
- 온보딩 화면에서 개발자 괴롭히기로 가는 버튼 추가
- vertical spacing이 이 페이지만 좀 다르게 되어있는데 [관련 슬랙](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1727258027636209)
=> Add sendFeedback button to `OnboardScene`

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, SNUTT-2022/SNUTT/Views/Components/KakaoMapView.swift, SNUTT-2022/SNUTT/Views/SNUTTApp.swift
- 카카오맵 패키지 버전 업그레이드 2.6.3 -> 2.12.3
- 강의 상세 페이지 진입 시 렌더링 문제로 지도가 종종 한번에 뜨지 않던 문제 개선
=> Update Kakaomap package

SNUTT-2022/SNUTT/Models/Bookmark.swift, SNUTT-2022/SNUTT/Services/SearchService.swift, SNUTT-2022/SNUTT/Services/TimetableService.swift, SNUTT-2022/SNUTT/ViewModels/MenuSheetViewModel.swift, SNUTT-2022/SNUTT/Views/Components/NotificationList.swift
- 시간표 전환 시에도 관심강좌 목록이 변하지 않는 문제 수정 ([관련 슬랙](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1736834360080139))
=> Fix bookmark not aligning with timetable

SNUTT-2022/SNUTT/Models/Lecture.swift
- 검색 도중 강의실 위치 UI가 계속 바뀌는 문제 수정([관련 슬랙](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1736501235120109))
=> Fix timeplace glitch while searching

SNUTT-2022/SNUTT/Models/Lecture.swift, SNUTT-2022/SNUTT/Models/SearchTag.swift, SNUTT-2022/SNUTT/Repositories/Dto/SearchTagDto.swift, SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift, SNUTT-2022/SNUTT/Repositories/Router/SearchRouter.swift, SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift, SNUTT-2022/SNUTT/Views/Components/Search/SearchTagsScrollView.swift, SNUTT-2022/SNUTT/Views/Scenes/FilterSheetScene.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
=> Add support for `categoryPre2025`

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj, SNUTT-2022/SNUTT/Assets/STFont.swift, SNUTT-2022/SNUTT/Extensions/String+Ext.swift, SNUTT-2022/SNUTT/Modifiers/PopoverTipModifier.swift, SNUTT-2022/SNUTT/Views/SNUTTApp.swift, SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
- 강의 상세 화면에서 강의평점 영역 탭하면 bottom sheet 뜨도록 수정([칸반](https://www.notion.so/wafflestudio/iOS-74b2d506ad5f4164a3da6de0bd3f8d5a?pvs=4))
=> Enable tap gesture for `ratingSection`

SNUTT-2022/SNUTT/Views/Components/KakaoMapView.swift
- 콘솔에 조용히 이런게 찍히고 있었네
- BUG IN CLIENT OF UIKIT: The caller of UIApplication.openURL(_:) needs to migrate to the non-deprecated UIApplication.open(_:options:completionHandler:). Force returning false (NO).
=> Fix lecture map not opening external app

SNUTT-2022/SNUTT/Views/Scenes/SharedUIAnalytics/AnalyticsEvent.swift, SNUTT-2022/SNUTT/Views/Scenes/SharedUIAnalytics/AnalyticsLogger.swift, SNUTT-2022/SNUTT/Views/Scenes/SharedUIAnalytics/AnalyticsScreen.swift, SNUTT-2022/SNUTT/Views/Scenes/SharedUIAnalytics/AnalyticsScreenModifier.swift
Slack: https://wafflestudio.slack.com/archives/C0PAVPS5T/p1741576644067429
=> 스크린 뷰 이벤트의 추가 매개변수는 별도 이벤트로 중복 로깅

SNUTT-2022/SNUTT/Repositories/AuthRepository.swift, SNUTT-2022/SNUTT/Repositories/Router/AuthRouter.swift, SNUTT-2022/SNUTT/Services/AuthService.swift
=> Remove `user_id` for `logout`

SNUTT/Modules/Feature/APIClientInterface/Sources/APIClientError.swift, SNUTT/Modules/Feature/AuthInterface/Sources/AuthState.swift, SNUTT/Modules/Utility/DependenciesUtility/Sources/BundleInfoDictionaryDependency.swift, SNUTT/Modules/Utility/DependenciesUtility/Sources/SynchronizedDeviceDependency.swift
앱의 기반 인프라 모듈들을 개선하여 안정성과 확장성을 향상시킵니다.
- APIClientError에 추가 에러 케이스 및 처리 로직 보강
- AuthState 모델 개선 및 상태 관리 최적화
- BundleInfoDictionaryDependency 개선
- SynchronizedDeviceDependency 최적화
- 의존성 주입 시스템 안정성 향상
- **Added lines**: ~25줄
- **Modified files**: 4개
- **Breaking changes**: 없음
```bash
tuist build
tuist test
```
=> ✨ 기반 인프라 모듈 개선

SNUTT/.gitignore, SNUTT/Modules/Feature/APIClientInterface/Sources/Middlewares/ErrorDecodingMiddleware.swift, SNUTT/Modules/Feature/Timetable/Sources/BusinessLogic/Application/LectureRepository.swift, SNUTT/Modules/Feature/Timetable/Sources/Infra/LectureAPIRepository.swift, SNUTT/Modules/Feature/Timetable/Sources/Presentation/BookmarkListViewModel.swift, SNUTT/Modules/Feature/Timetable/Sources/Presentation/ExpandableLectureListViewModel.swift, SNUTT/Modules/Feature/Timetable/Sources/Presentation/LectureListViewModel.swift, SNUTT/Modules/Feature/Timetable/Sources/Presentation/LectureSearchViewModel.swift, SNUTT/Modules/Feature/Timetable/Sources/UI/ExpandableLectureList/ExpandableLectureListView.swift, SNUTT/Modules/Feature/Timetable/Sources/UI/LectureSearch/BookmarkListView.swift, SNUTT/Modules/Feature/Timetable/Sources/UI/LectureSearch/EmptyBookmarkView.swift, SNUTT/Modules/Feature/Timetable/Sources/UI/LectureSearch/LectureSearchResultScene.swift, SNUTT/Modules/Feature/Timetable/Sources/UI/TimetableScene.swift, SNUTT/Modules/Feature/TimetableInterface/Sources/Models/Lecture.swift
- 북마크 API 추가 및 연동
- 북마크 UI 구현 (북마크 리스트 뷰, 빈 북마크 뷰)
- 북마크 토글 기능 구현
- 500 이상 에러 발생시 서버 오류 알러트 표시
- 강의 검색 결과 화면 개선
- 확장 가능한 강의 리스트 컴포넌트 추가
- 테마 설정 UI 개선
- 메뉴 시트 컴포넌트 개선
- 모듈화 구조 개선
- 의존성 주입 시스템 개선
- API 클라이언트 미들웨어 추가
- 시간표 위젯 UI 개선
- 위젯 데이터 소스 개선
=> ✨ 북마크 기능 구현 및 UI 개선

SNUTT-2022/SNUTT/Views/Components/Lecture/ExpandableLectureCell.swift
- 북마크 해제할 때 강의 상세 sheet dismiss되는 문제 수정
- before
https://github.com/user-attachments/assets/5c03a2ae-6c40-4483-8cb6-2a03d8d22a76
- after
https://github.com/user-attachments/assets/052b3bef-37a1-44c6-86fe-56a954a94bd2
=> Fix sheet animation glitch (remove bookmark)

.github/workflows/build-legacy.yml
=> Remove test action from github workflow
