SNUTT/MenuViewController.swift
SNUTT/STTimetableTabViewController.swift

"시간표가 안 떠요" 이슈들에 대한 해결
- fetch current timetable이 로그인 할 때만 호출됨
- api가 업데이트 되거나, userDafault가 업데이트 됐음에도, 이미 로그인한 상태이기 때문에 current timetable을 호출하지 않아 current timtable을 기반으로 작성된 로직들이 작동하지 않았던 것으로 보임
- 주요 view load에 fetch current timetable api 호출
api 호출 코드, current timetable 코드가 너무 복잡하게 얽혀 있음. 리팩토링이 시급하다.

Fix current timetable issue [SNUTT-305]

---

SNUTT/STTimetableTabViewController.swift

- 시간표 테마를 변경할 때 "적용" 버튼을 누르지 않고 회색 화면을 탭하여 시간표 테마 정하기에서 빠져나갈 경우 원래 테마가 아니라 기본 테마가 적용되는 문제가 있었습니다. (앱을 재시작하면 정상 작동합니다)
- 메뉴탭에서 시간표를 변경했을 때 `originalTheme`의 값이 업데이트되지 않아 발생한 문제였습니다.
- `hidesBackgroundCoverView()`에서 originalTheme을 설정하도록 하는 코드를 추가했습니다.

시간표 테마 변경 관련 문제 수정 [SNUTT-394]

---

SNUTT/SNUTT/AppDelegate.swift

- 탭바의 StandardAppearance 설정을 추가하였습니다. iOS 15부터는 기본적으로 탭바가 transparent하게 설정되어 발생하는 문제였습니다.

Fix transparent tabBar issue [SNUTT-400]

---

SNUTT/SNUTT/Review/ReviewViewController.swift
SNUTT/SNUTT/STMainTabBarController.swift

웹뷰 Tab 버튼을 눌렀을 때, 웹뷰 전체를 리로드하도록 로직을 바꿨습니다.

Fix webview reload issue [SNUTT-342]

---

SNUTT/SNUTT/STLectureTableViewCell.xib

- 강의명 label의 trailing을 `-학점` 라벨의 leading 기준으로 하도록 변경하였습니다.

강의 목록에서 긴 강의명의 UI 깨짐 현상 해결 [SNUTT-423]

---

SNUTT/SNUTT/STLectureSearchTableViewCell.xib

- Before
- After
https://user-images.githubusercontent.com/70614553/161882926-6802d6c1-6806-4f8f-a466-b08fc00cd9e4.mp4

강의 검색에서 긴 강의명 UI 깨짐 현상 해결 [SNUTT-426]

---

SNUTT/SNUTT/STTimetable.swift

- UserDefault에 시간표를 저장할 때 theme 값은 저장이 안되고 있어서 해당 부분 수정해주었습니다.

위젯에 테마 반영되도록 수정 [SNUTT-415]

---

SNUTT/SNUTT/STSingleClassTableViewCell.swift
SNUTT/SNUTT/STSingleLectureTableViewController.swift

- 기존에 있던 `custom`이라는 필드를 보면 원래 실제 강의는 수정 못하도록 되어 있었던 것 같은데, 왜인진 모르겠지만 이 값이 무조건 `true`로 설정되어 있었습니다.
- 그래서 해당 로직이 잘 작동하도록 `custom` 필드를 `customLecture`로 교체해주었습니다.

실제 강의 시간은 수정하지 못하도록 변경 [SNUTT-445]

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT.xcworkspace/contents.xcworkspacedata
SNUTT-2022/SNUTT.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
SNUTT-2022/SNUTT/AppState/AppState.swift
SNUTT-2022/SNUTT/Models/DrawingSetting.swift
SNUTT-2022/SNUTT/Models/Setting.swift
SNUTT-2022/SNUTT/Models/System.swift
SNUTT-2022/SNUTT/Models/Timetable.swift
SNUTT-2022/SNUTT/Models/TimetableSetting.swift
SNUTT-2022/SNUTT/Models/User.swift
SNUTT-2022/SNUTT/ViewModels/MyLectureListViewModel.swift
SNUTT-2022/SNUTT/ViewModels/ReviewViewModel.swift
SNUTT-2022/SNUTT/ViewModels/SettingViewModel.swift
SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift
SNUTT-2022/SNUTT/Views/Components/LectureDetails.swift
SNUTT-2022/SNUTT/Views/Components/LectureList.swift
SNUTT-2022/SNUTT/Views/Components/LectureListCell.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlock.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlocksLayer.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableGridLayer.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableZStack.swift
SNUTT-2022/SNUTT/Views/SNUTTApp.swift
SNUTT-2022/SNUTT/Views/Scenes/MyLectureListScene.swift
SNUTT-2022/SNUTT/Views/Scenes/MyTimetableScene.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SettingScene.swift

얘기했던 방식으로 AppState - ViewModel - View 데이터 플로우를 수정했습니다. View의 렌더링을 디버깅해보니 stateless View들은 각 View 안에서 참조하는 ViewModel 값이 변경될 때만 다시 렌더링되는 것 같습니다. AppState의 @published 변수가 바뀐다고 해서 모든 뷰가 리렌더링 되지는 않네요.
https://user-images.githubusercontent.com/54926767/175579822-23f9e2d7-a7ae-47d4-a0f2-a5f93a55c6bc.mov
데이터 플로우는 만들었으나, 아직 수정할 사항이 있습니다.
~~1. AppState 안의 class 데이터 타입들을 AppState 바깥으로, Model로 빼내기~~
~~2. `SNUTTApp.swift`에서 TabItem 선언 방식 바꾸기~~
3. 그 외에 부자연스러운 것 수정..
아침에 마저 해보겠습니다..
그리고 Workspace에 project를 추가했습니다.

Fix data flow with AppState [SNUTT-456]

---

SNUTT/SNUTT/STErrorCode.swift
SNUTT/SNUTT/STLecture.swift
SNUTT/SNUTT/STLectureRouter.swift
SNUTT/SNUTT/STNetworking.swift
SNUTT/SNUTT/STPeriod.swift
SNUTT/SNUTT/STSwiftyJSONRequest.swift
SNUTT/SNUTT/STTimetable.swift
SNUTT/SNUTT/STTimetableManager.swift

- 강의(일반 강의 및 커스텀 포함)를 추가하고자 할 때와 커스텀 강의시간을 수정할 때, 시간표에 겹치는 시간대가 있는 경우 중복된 강의들을 모두 덮어쓸 수 있는 선택지를 제공합니다.
- 기존 코드에서 server의 응답에 따라 AlertView를 띄우는 로직이 `STSwiftyJSONRequest`에 위치하고 있어 `confirmAction`과 `cancelAction` parameter를 추가하는 방식으로 구현하였습니다. 이번 PR에서는 `cancelAction`이 사용될 일이 없지만 추후 확장성을 위하여 추가하였습니다.
https://user-images.githubusercontent.com/70614553/176494978-58ca9000-99b6-48cf-b6e9-b69415b488c9.mp4

중복된 강의 덮어쓰기 구현 [SNUTT-455]

---

SNUTT/SNUTT/MenuViewController.swift
SNUTT/SNUTT/STErrorCode.swift

시간표를 생성할 때 이름이 비어있거나 다른 시간표의 이름과 중복되면 `STSwiftyJSONRequest`와 `MenuViewController`에서 한번씩 alert를 띄워서 두 개의 alert가 뜨는 문제가 있었습니다. 아래 영상에서는 비어있는 시간표 이름에 대해서만 녹화되어있는데 중복된 이름의 시간표에서도 동일한 문제가 발생합니다.
https://user-images.githubusercontent.com/70614553/177199193-6cbe89c8-b8df-4a35-9bc2-a37536abec06.mp4

시간표 생성할 때 비어있거나 중복된 이름일 경우 alert가 두 번 뜨는 문제 [SNUTT-467]

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT/AppState/AppEnvironment.swift
SNUTT-2022/SNUTT/AppState/AppState.swift
SNUTT-2022/SNUTT/Assets/STColor.swift
SNUTT-2022/SNUTT/Models/Lecture.swift
SNUTT-2022/SNUTT/Models/Theme.swift
SNUTT-2022/SNUTT/Models/TimePlace.swift
SNUTT-2022/SNUTT/Models/Timetable.swift
SNUTT-2022/SNUTT/Models/TimetableSetting.swift
SNUTT-2022/SNUTT/Models/Weekday.swift
SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift
SNUTT-2022/SNUTT/Services/TimetableService.swift
SNUTT-2022/SNUTT/ViewModels/MyLectureListViewModel.swift
SNUTT-2022/SNUTT/ViewModels/ReviewViewModel.swift
SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift
SNUTT-2022/SNUTT/Views/Components/LectureListCell.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/LectureBlocks.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlock.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlocksLayer.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableZStack.swift
SNUTT-2022/SNUTT/Views/SNUTTView.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureListScene.swift
SNUTT-2022/SNUTT/Views/Scenes/MyLectureListScene.swift
SNUTT-2022/SNUTT/Views/Scenes/MyTimetableScene.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift
SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

- AppState의 `currentTimetable`을 `TimetableSetting`의 하위로 옮겼습니다. 스프린트에서는 `@Published var currentTimetable: Timetable`과 같이 선언한 뒤에 AppState를 `ObservableObject`를 만드는 쪽으로 얘기했었지만, 그렇게 하면 View에서 AppState를 직접 구독해야 합니다. `TimetableSetting`으로 옮기는 것이 의미상으로도, 통일성의 측면에서도 적절하다고 판단했고요.
- currentTimetable은 Optional로 변경했습니다. 그렇게 하지 않으면 초기에 currentTimetable을 얻어올 때까지 `init()` 태스크가 block되므로 앱 시작 속도에 악영향이 있을 것이라고 생각했습니다. 
- Service의 역할을, `Repository를 통해 API 호출 - DTO를 Model로 변환 - AppState를 적절히 변경`에 한정했으며, 나머지 로직은 뷰모델에서 수행하도록 구현했습니다.
- Repository에서 API 호출하는 동안에 발생하는 에러는, 계속해서 `throw`하다가 ViewModel에서 `catch`하여 핸들링하도록 구현했습니다.
- 구체적인 에러 핸들링 로직은 #88 에서 구현했습니다.
- `async` 함수는 View의 `.task()` modifier에서 호출하도록 구현했습니다.

API 연동 및 에러 처리 [SNUTT-470]

---

SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift

- 강의 삭제 전 Alert를 띄우고,
- 강의 편집 모드에서는 `강의평`, `강의계획서`와 같은 버튼들이 보이지 않도록 했습니다.

강의 삭제 전 Alert 띄우기

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT/AppState/AppEnvironment.swift
SNUTT-2022/SNUTT/AppState/States/UserState.swift
SNUTT-2022/SNUTT/Repositories/NetworkUtils.swift
SNUTT-2022/SNUTT/Services/AuthService.swift
SNUTT-2022/SNUTT/Services/TimetableService.swift
SNUTT-2022/SNUTT/ViewModels/ReviewViewModel.swift
SNUTT-2022/SNUTT/Views/SNUTTApp.swift
SNUTT-2022/SNUTT/Views/SNUTTView.swift
SNUTT-2022/SNUTT/Views/Scenes/LoginScene.swift
SNUTT-2022/SNUTTTests/AuthRepositoryTests.swift
SNUTT-2022/SNUTTTests/TestUtils.swift
SNUTT-2022/SNUTTTests/TimetableRepositoryTests.swift

- #120 에서 분기한 브랜치입니다.
주요 변경사항은 아래와 같습니다.
- AuthService를 추가했습니다. 
- token이 주입되고 관리되는 방식을 변경했습니다.
- (기존) `AppEnvironment`의 `bootstrap` 과정에서 생성하는 `Session`에 토큰 주입
- (문제) 토큰이 변경되었을 경우, 새로운 토큰으로 `Session` 객체를 다시 생성한 뒤 Repository들을 돌면서 Session을 교체하거나,  `(session.intercepter as! Intercepter).authStorage.token = newToken`과 같이 다소 번거롭게 수정해야 함
- (수정) `AuthStorage` 대신 `UserState`가 token에 대한 single source of truth로 작동하게끔 변경. `Intercepter`는 `userState`를 참조해서 token을 실시간으로 헤더에 반영하도록 함. 이에 따라 `AuthStorage`와 하위 구현체들은 삭제.
- `token` -> `accessToken`으로 리네임 (fcmToken, Apple Token 등과 구분하기 위해)
- `UserState`에 `apiKey`가 있는데, 이건 state가 아니라 앱의 환경변수에 가까우므로 추후에 deprecate할 예정입니다.
- 아주 간단한 로그인 뷰를 추가했습니다. (화면 전환 등 기능 잘 작동하는지 확인용)
- Auth 관련 테스트 일부 작성
- `@testable import SNUTT`를 사용하면 타겟 멤버십에 SNUTTTest를 추가할 필요가 없습니다. 이에 따라 …

AuthService 구현, 토큰 관리 방식 변경

---

SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift

기존 스누티티처럼 autofit인 경우에도 10~18을 기본으로 유지하도록 수정했습니다

AutoFit 시작시간/끝나는 시간 수정

---

SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureCell.swift

- sheet를 dismiss할 때 이상한 버그가 있어서 수정했습니다.
- https://stackoverflow.com/questions/65390267/swiftui-sheet-not-animating-dismissal-on-macos-big-sur
https://user-images.githubusercontent.com/33917774/202913542-83097ca0-41ab-4650-b44d-81e35e1647ae.mov

Fix animation glitch when dismissing sheet

---

SNUTT-2022/SNUTT/AppState/AppEnvironment.swift
SNUTT-2022/SNUTT/Extensions/UserDefaults+ext.swift
SNUTT-2022/SNUTT/Repositories/Router/UserRouter.swift
SNUTT-2022/SNUTT/Repositories/UserDefaultsRepository.swift
SNUTT-2022/SNUTT/Repositories/UserRepository.swift
SNUTT-2022/SNUTT/Services/AuthService.swift
SNUTT-2022/SNUTT/Services/UserService.swift

- 로그인 시 생성되는 fcmToken을 서버로 저장하도록 구현했습니다.

FCM device registration 구현

---

.github/workflows/deploy.yml
SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
SNUTT-2022/fastlane/Fastfile

- Firebase SDK가 xcode 14 대응 버전업을 하면서 bitcode라는 것을 빼버렸는데, 이것때문에 CD가 실패하는 것 같아서 fastfile을 수정했습니다.

Include bitcode when archiving

---

SNUTT-2022/SNUTT/Repositories/AuthRepository.swift
SNUTT-2022/SNUTT/Repositories/Router/AuthRouter.swift
SNUTT-2022/SNUTT/Services/AuthService.swift
SNUTT-2022/SNUTT/ViewModels/OnboardViewModel.swift
SNUTT-2022/SNUTT/Views/Components/AnimatedTextField.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/AccountSettingScene.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/TimetableSettingScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SignUpView.swift

- 로그아웃, 회원탈퇴 시 alert 추가
- (1) 회원가입 (2) 아이디/비밀번호 추가 -> 이 2가지 경우에서 이메일 필수 필드로 변경 ([관련 슬랙 스레드](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1668232280648599))
- 환경설정 > 시간표 설정에서 `자동맞춤`이 비활성화된 경우에만 시간표 범위 수정할 수 있도록 수정 (아래 영상 참고)
https://user-images.githubusercontent.com/70614553/203056968-c33f0dd2-eaf9-4840-bdfe-eca33ea09f91.mp4

로그아웃, 회원탈퇴 시 alert / 이메일 필수로 변경 / 시간표 설정 자동맞춤 대응

---

SNUTT-2022/SNUTT/Repositories/AuthRepository.swift
SNUTT-2022/SNUTT/Repositories/Dto/AuthDto.swift
SNUTT-2022/SNUTT/Repositories/Router/AuthRouter.swift
SNUTT-2022/SNUTT/Repositories/Router/UserRouter.swift
SNUTT-2022/SNUTT/Repositories/UserDefaultsRepository.swift
SNUTT-2022/SNUTT/Repositories/UserRepository.swift
SNUTT-2022/SNUTT/Services/AuthService.swift
SNUTT-2022/SNUTT/Services/UserService.swift
SNUTT-2022/SNUTT/ViewModels/AccountSettingViewModel.swift
SNUTT-2022/SNUTT/ViewModels/OnboardViewModel.swift
SNUTT-2022/SNUTT/Views/Scenes/LoginScene.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/AccountSettingScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SignUpView.swift
SNUTT-2022/SNUTTTests/AuthRepositoryTests.swift

- `id`, `token`, `userId` 등 하나의 변수가 맥락에 따라 다른 의미를 가지는 경우가 있어서, 각 변수명이 좀 더 분명한 의도를 갖도록 수정했습니다.
- 바뀐 변수명은 아래와 같습니다.
- `id` -> `localId`, `fbId`
- `token` -> `appleToken`, `fbToken`, `accessToken`
- `userId` -> `userId` (이것은 유저 entity의 primary key 필드를 의미하는데, 마땅한 다른 이름이 생각나지 않아 유지했습니다)

Auth 변수명 리팩토링

---

SNUTT-2022/SNUTT/Models/Lecture.swift
SNUTT-2022/SNUTT/Models/TimePlace.swift
SNUTT-2022/SNUTT/Models/Timetable.swift
SNUTT-2022/SNUTT/Repositories/Dto/TimetableDto.swift
SNUTT-2022/SNUTT/Utils/TimeUtils.swift
SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift
SNUTT-2022/SNUTT/ViewModels/LectureListViewModel.swift
SNUTT-2022/SNUTT/Views/Components/LectureDetail/EditableFields.swift
SNUTT-2022/SNUTT/Views/Components/LectureListCell.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureCell.swift
SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureTimeSheetScene.swift

- `start`, `len`의 흔적을 없앴습니다.
- [여기](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1664813491365339)에서 언급했던 것처럼 시간 표기 로직도 업데이트했습니다.

강의 시간 로직 변경

---

SNUTT-2022/SNUTT/Models/Lecture.swift
SNUTT-2022/SNUTT/ViewModels/SearchSceneViewModel.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureCell.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureList.swift
SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift

- 강의 검색 결과에서 시간표에 이미 존재하는 강의인 경우 `제거하기` 버튼을 사용할 수 있도록 수정했습니다.

강의 검색 결과에서 `제거하기` 버튼 추가

---

.github/workflows/build.yml
.github/workflows/deploy.yml
SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

- 앱스토어/테스트플라이트 배포를 위한 아카이빙은 xcode 14.1 버전을 사용하도록 변경했습니다.
- test, build 는 13.4.1과 14.1 환경 모두에서 진행하도록 변경했습니다.
---
@peng-u-0807 
- #178 에서 13.4.1 버전 호환성 문제를 해결한 줄 알았지만.. dSym 파일을 Crashlytics에 자동으로 업로드하도록 프로젝트 세팅을 변경하는 과정에서 또다른 문제가 발생해서 아카이빙 자체는 14버전으로 진행하고자 합니다.
- 그리고 제가 벤투라로 올려버려서 더이상 13.4.1 버전 설치가 안되네요 😢

Xcode 14.1 버전으로 Archiving 하도록 변경

---

SNUTT-2022/SNUTT/Models/Lecture.swift
SNUTT-2022/SNUTT/ViewModels/SearchSceneViewModel.swift

- #187 에서 `Lecture`가 Equitable이 되어서 뷰 리렌더가 제대로 발생하지 않게 되었습니다. 이에 대한 버그 픽스입니다.

Make Lecture non-Equitable

---

SNUTT-2022/SNUTT/Services/LectureService.swift
SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift

- #153 에서 발생한 버그를 수정합니다.
- `alert`에서 비동기적으로 바뀌는 View의 상태에 의존하면서 inconsistency가 발생했던 것이 원인이었습니다.

LectureDetailScene에서 겹치는 강의 Override 안되는 문제 수정

---

.github/workflows/deploy.yml
SNUTT-2022/fastlane/Fastfile

- release note를 fetching할 때에 CI서버에서 rate limit에 걸리는 경우가 많아 일단 제 개인 PAT를 secret에 추가했습니다. 아무 scope도 추가하지 않아서 public 정보에 대한 read-only access밖에 없긴 합니다.

Authenticate API requests for git release notes

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT/AppState/AppState.swift
SNUTT-2022/SNUTT/AppState/States/ReviewState.swift
SNUTT-2022/SNUTT/AppState/States/UserState.swift
SNUTT-2022/SNUTT/Repositories/NetworkConfiguration.swift
SNUTT-2022/SNUTT/Repositories/ReviewRepository.swift
SNUTT-2022/SNUTT/Services/GlobalUIService.swift
SNUTT-2022/SNUTT/Services/LectureService.swift
SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift
SNUTT-2022/SNUTT/ViewModels/SearchSceneViewModel.swift
SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureCell.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureList.swift
SNUTT-2022/SNUTT/Views/Components/WebViews/ReviewWebView.swift
SNUTT-2022/SNUTT/Views/Components/WebViews/WebViewProtocol.swift
SNUTT-2022/SNUTT/Views/Components/WebViews/WebViewType.swift
SNUTT-2022/SNUTT/Views/SNUTTView.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift
SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

- 웹뷰를 Preloading함으로써 웹뷰가 뜨는 체감 속도를 최대한 높여보았습니다.
- WebView과 관련 객체들을 전역 AppState로 옮겼으며, `WebViewPreloadManager` 객체가 이를 관리하도록 했습니다. (물론 더 나은 이름이 있다면 제안받습니다.)
- 메인 웹뷰 하나, 디테일 웹뷰 하나 이렇게 총 두개의 `WebViewPreloadManager`가 존재합니다.
- 검색 화면에서 디테일 웹뷰를 열 때 다른 화면이 순간적으로 보이는 문제가 있습니다. 네이티브쪽 문제도 있는데, 웹뷰쪽에서 해결이 가능한 부분도 있는 것 같습니다(아래 영상 참고).
- 디테일 웹뷰를 dismiss하는 bridge를 연결했습니다.
- 쿠키 날라가는 문제에 도움이 될까 싶어서 cookie expire date를 설정해주었습니다.
https://user-images.githubusercontent.com/33917774/209569178-bc8cd01f-ea05-4e6d-af84-a1b02ecfd772.MP4
https://user-images.githubusercontent.com/33917774/209569182-61e38b18-7d4f-4df6-9367-277c052aaa96.MP4
https://user-images.githubusercontent.com/33917774/209569437-e310f709-98d7-46e3-ab1f-7a4a03059a96.MP4
- @woohm402 이 부분은 웹뷰에서 처리가 가능할 것 같은데, 한번 봐주실 수 있나요?
- iOS 버그로 인해 Sheet을 내린 후에 …

Refactor webviews (feat. preloading, bridge, etc.)

---

SNUTT-2022/SNUTT/AppState/States/ReviewState.swift
SNUTT-2022/SNUTT/AppState/States/SystemState.swift
SNUTT-2022/SNUTT/Models/ErrorCode.swift
SNUTT-2022/SNUTT/Services/AuthService.swift
SNUTT-2022/SNUTT/Services/GlobalUIService.swift
SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift
SNUTT-2022/SNUTT/ViewModels/SearchSceneViewModel.swift
SNUTT-2022/SNUTT/ViewModels/TimetableViewModel.swift
SNUTT-2022/SNUTT/Views/Components/Search/SearchLectureCell.swift
SNUTT-2022/SNUTT/Views/SNUTTView.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift
SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

- 검색 리스트에서 강의평으로 바로 이동할 때, 이메일 미인증 사용자의 경우에는 강의평 탭에서 이메일 인증 진행하도록 플로우 변경
- 로그아웃할 때 초기화되어야 할 정보가 초기화되지 않는 문제 수정

이메일 미인증시 CTA 개선

---

SNUTT-2022/SNUTT/ViewModels/SettingViewModel.swift
SNUTT-2022/SNUTT/Views/Components/UserSupportView.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/SettingScene.swift

- `개발자 괴롭히기`에서 유저 이메일이 있는 경우에는 자동으로 필드를 채워주고+수정 불가능, 유저 이메일이 없는 경우에만 직접 입력하도록 수정
- 문의 내용이 긴 경우 keyboard를 dismiss할 수 없었던 문제 수정

`개발자 괴롭히기` 이메일 자동 입력

---

SNUTT-2022/SNUTT/Extensions/ColorScheme.swift
SNUTT-2022/SNUTT/Views/Components/WebViews/WebViewProtocol.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift

- `WKWebsiteDataStore`가 `nonPersistent`로 설정되어 있는 것이 최근 에러의 원인일 가능성이 커보입니다. 
- 아마 SNUTT 2.0의 코드를 복붙해오다가 포함된 것 같은데, 혹시 이게 `nonPersistent`로 설정되어야 할 이유가 있었나요? @peng-u-0807 
- #215 여기서는 매번 쿠키를 리셋해주도록 했는데, 일단 이 PR로 해결이 안된다면 저 방식으로 다시 시도해야 할 것 같아요.
- Theme 쿠키를 조금 더 일찍 주입하도록 변경했습니다.

웹뷰 쿠키 관련 문제 수정

---

SNUTT-2022/SNUTT/AppState/States/ReviewState.swift
SNUTT-2022/SNUTT/AppState/States/SystemState.swift
SNUTT-2022/SNUTT/Views/Components/WebViews/WebViewProtocol.swift
SNUTT-2022/SNUTT/Views/Scenes/ReviewScene.swift

(신형 아이폰 / 시뮬레이터에서는 재현 잘 안됨)
1. 강의평 탭 열어놓은 상태에서
2. 카메라 앱을 열고 비디오를 20초간 찍는다
3. 스누티티 앱으로 돌아간다
4. (메모리 부족으로) 웹뷰가 리프레시되면서 쿠키 날라가고 고양이 등장
3.1.1 이상부터는 cookie store가 `nonPersistent`로 설정되어 있는 문제를 수정(#216)했기 때문에 위 이슈는 재현되지 않습니다.
다만 1) SwiftUI 뷰가 리프레시되는 시점, 웹뷰가 리프레시되는 시점, `theme` 쿠키가 주입되는 시점이 모두 다르고, 2) 뷰 리프레시 도중에 시스템 `colorScheme`을 읽을 때 부정확한 값이 읽히는 버그 때문에 웹뷰 테마가 정확하게 동기화되지 않는 문제가 있었습니다.
이 문제는 colorScheme의 변경을 처리하는 eventSignal을 debouncing 처리해주어서 해결했습니다.
그리고 아직 고양이 웹뷰가 메모리에 남아있는 상태에서 preloading을 계속 해주게 되면 트러플로 스팸이 갈 것 같아서 웹뷰 접근할 때마다 쿠키를 리셋해주는 코드도 추가했습니다.

웹뷰 쿠키 관련 개선

---

SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableUtils.swift

Resolves #224 
- 시간표가 비어있는 경우에는 자동 맞춤 모드와 관계 없이 기본적으로 9-17시를 보여주고, 월-금을 보여주도록 합니다

Fix wrong start-end time, weekday for empty timetable

---

SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogListScene.swift
SNUTT-2022/SNUTT/Debug/NetworkInspector/NetworkLogStore.swift
SNUTT-2022/SNUTT/Views/Components/NotificationList.swift
SNUTT-2022/SNUTT/Views/Components/NotificationListCell.swift

SwiftUI 버그로 추정
(+ 잠수함패치로 네트워크 로그에 초기화 버튼 추가)
| AS-IS | TO-BE |
|:-----:|:-----:|
| ![AS-IS Image](https://github.com/wafflestudio/snutt-ios/assets/33917774/78fe03f0-63a4-429d-847b-c4c8316be4d5) | ![TO-BE Image](https://github.com/wafflestudio/snutt-ios/assets/33917774/639c6ab7-d665-4ce8-af8c-bfb77a48daca) |

Notification cell height 계산 잘못되는 버그 수정

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1693843644674349
- ios-rn-prebuilt 버전 업데이트 
- 다크모드 전환 시 RN 뷰 리로드

Fix RN background color issue

---

SNUTT-2022/SNUTT/AppState/DeepLinkHandler.swift

- 친구 관련 푸시 알림을 탭하는 경우에는 친구 탭으로 곧장 이동합니다

Add support for `friends` notification deeplink

---

SNUTT-2022/SNUTT/Services/PopupService.swift

다음과 같이 변경
- 서버 팝업 데이터 기준으로,
- 동일한 key에 해당하는 Popup이 로컬에 있으면 로컬 데이터 사용, 없으면 (당연히) 서버 데이터 사용
- 그런데 로컬 팝업 데이터와 서버 데이터 사이에 `hidden_days` 차이가 있으면 서버 데이터 사용 (안보기 타이머는 초기화)

Fix popup logic

---

SNUTT-2022/SNUTT.xcodeproj/project.pbxproj
SNUTT-2022/SNUTT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

https://github.com/wafflestudio/ios-rn-prebuilt/releases/tag/0.6.0
이거 사용하도록 업데이트했어요

RN Async Storage 추가

---

SNUTT-2022/SNUTT/ViewModels/LectureDetailViewModel.swift
SNUTT-2022/SNUTT/Views/Scenes/Settings/ColorSchemeSettingScene.swift

- `강의 검색 > 강의 하나 선택 > 자세히 > 빈자리 알림 버튼 터치` 시 빈자리 알림을 신청할 수 없는 학기에 대한 alert 뜨지 않는 문제 수정
- 추가로 환경설정 탭에서 `색상 모드` -> `화면 모드` 문구 변경 (피그마 따라서)

Fix alert not showing for invalid semester(vacancy)

---

SNUTT-2022/SNUTT/Views/Components/Timetable/TimetableBlock.swift

- "장소" 라벨의 line limit을 없애고 scaling을 조정했습니다

Fix small place label

---

SNUTT-2022/SNUTT/Models/STNotification.swift
SNUTT-2022/SNUTT/Repositories/Dto/NotificationDto.swift

- `title` 값이 비어있는 예전의 알림들에 대해서는 default title값을 사용하도록 수정했습니다

Fix default value for empty notification title

---

SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift

- 강의평 확인을 위한 이메일 인증이 완료되지 않았을 때, "이메일 인증으로 바로 가기"에 대해 강의 상세 뷰(sheet)가 dismiss되지 않던 문제 수정

Fix sheet not dismissing (email verification)

---

SNUTT-2022/SNUTT/Views/Components/Search/SearchTips.swift
SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift
SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableCompactWidgetView.swift
SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableFullWidgetView.swift
SNUTT-2022/SNUTTWidget/TimetableWidget/TimetableWidget.swift

- iOS 17+에서 위젯 배경에 패딩 들어가있던 문제 수정 (슬랙 링크 못찾겠어서 사진으로 대체..)
- 강의 검색 화면에서 바깥쪽 누르면 키보드 내려가도록 수정 ([피드백](https://wafflestudio.slack.com/archives/C8M9NUBBR/p1706507366989269))

Fix widget padding + dismiss keyboard if `SearchTips` area is touched

---

SNUTT-2022/SNUTT/Views/Components/FilterSheetContent.swift
SNUTT-2022/SNUTT/Views/Components/TimeRangeSelectionSheet.swift
SNUTT-2022/SNUTT/Views/Scenes/FriendsScene.swift

- 아이폰 X 이전 기기에 대해서 `TimeRangeSelectionSheet`의 상단의 빈 공간 삭제
- 아이폰 X 이전 기기 및 silicon mac에서 친구 탭 상단의 빈 공간도 삭제

Fix NavigationBarTitle space

---

SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

- 친구 기기에서 TimetableScene toolbar overflow를 발견했는데 toolbar로는 [해결이 어려워서](https://developer.apple.com/documentation/swiftui/toolbaritemplacement) HStack으로 변경
- 관련 이미지

Fix Toolbar spacing

---

SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

- [슬랙](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1726157731070059)에서 제보된 UI 차이가 있어서 custom toolbar에서 그냥 `.toolbar`로 돌아왔습니다
- `.toolbar` 시절 사용하던 코드랑 큰 차이 없는데 그동안 문제 있었던 기종+iOS에서 재발X

Revert custom toolbar

---

SNUTT-2022/SNUTT/Assets/STColor.swift
SNUTT-2022/SNUTT/Views/Scenes/TimetableScene.swift

시간표 탭에서 상세 화면 한번 들어갔다 나오면 상단탭이 다 가운데로 쏠리는 버그 수정
(이전에도 종종 나왔던 버그인데 여태까진 랜덤 재현됐다가 비교적 최신 OS에서는 확정적으로 재현됨)
- ToolbarItem으로는 시간표 제목의 overflow 대응+올바른 spacing 모두 잡기 어려워서 이전에 사용했던 HStack으로 돌아갔습니다
- iOS 16.0, 17.0, 18.0 에서 문제 없는 것 확인

Change `Toolbar` to `HStack`

---

SNUTT-2022/SNUTT/Services/SearchService.swift
SNUTT-2022/SNUTT/ViewModels/SearchLectureSceneViewModel.swift
SNUTT-2022/SNUTT/Views/Components/FilterSheetContent.swift
SNUTT-2022/SNUTT/Views/Scenes/FilterSheetScene.swift
SNUTT-2022/SNUTT/Views/Scenes/LectureDetailScene.swift
SNUTT-2022/SNUTT/Views/Scenes/SearchLectureScene.swift

- 교양영역 관련 [기획 수정사항](https://wafflestudio.slack.com/archives/C0PAVPS5T/p1738309826932779) 반영
- ~2024년: `교양영역`
- 2025년~: `교양영역`, `구) 교양영역`

Fix: do not show `categoryPre2025` before 2025

---

SNUTT-2022/SNUTT/Info.plist

- 강의 업데이트 알림에 대한 딥링크가 동작하지 않는 문제 수정

Fix `.lectureUpdate` deeplink not working

---

SNUTT-2022/SNUTT/Modifiers/PopoverTipModifier.swift

- iOS 18~ 쯤부터 Popover tip이 이상하게 뜨길래(파란 tint, 정렬 안맞음 등...) 스타일 지정
- Before(왼쪽), After(오른쪽)

Fix popover tip style

---

SNUTT/Modules/Feature/APIClient/Tests/APIClientTests.swift
SNUTT/Modules/Feature/Auth/Tests/AuthTests.swift
SNUTT/Modules/Feature/Configs/Tests/ConfigsTests.swift
SNUTT/Modules/Feature/Notifications/Tests/NotificationsTests.swift
SNUTT/Modules/Feature/Popup/Tests/PopupTests.swift
SNUTT/Modules/Feature/Themes/Tests/ThemesTests.swift
SNUTT/Modules/Feature/Timetable/Tests/TimetableTests.swift
SNUTT/Modules/Feature/TimetableUIComponents/Tests/TimetableUIComponentsTests.swift
SNUTT/Modules/Feature/Vacancy/Tests/VacancyTests.swift
SNUTT/Modules/Shared/SharedAppMetadata/Tests/SharedAppMetadataTests.swift
SNUTT/Modules/Shared/SharedUIComponents/Tests/SharedUIComponentsTests.swift
SNUTT/Modules/Utility/DependenciesUtility/Tests/DependenciesUtilityTests.swift
SNUTT/Modules/Utility/FoundationUtility/Tests/FoundationUtilityTests.swift
SNUTT/Modules/Utility/SwiftUIUtility/Tests/SwiftUIUtilityTests.swift
SNUTT/Modules/Utility/UIKitUtility/Tests/UIKitUtilityTests.swift
SNUTT/SNUTT/Tests/SNUTTTests.swift
SNUTT/Tuist/Templates/feature/FeatureTests.stencil
SNUTT/Tuist/Templates/shared/SharedTests.stencil
SNUTT/Tuist/Templates/utility/UtilityTests.stencil

테스트 프레임워크를 XCTest에서 Swift-Testing으로 마이그레이션합니다.
- 모든 모듈의 테스트 파일을 Swift-Testing 문법으로 변경
- `XCTAssertEqual` → `#expect` 문법 적용
- 테스트 템플릿 파일들도 함께 업데이트
- NotificationsTests 디렉토리 추가
- **Added lines**: ~60줄
- **Modified files**: 20개
- **Breaking changes**: 없음
```bash
tuist test
```

♻️ XCTest에서 Swift-Testing으로 마이그레이션
